### ISSUE TITLE
你面板里的SS-LIBEV版本太老了，我在这里修改了参数部署SS-LIBEV，ss-libev就是3.30版本了吗？

### ISSUE THREAD

**Issue by embeddedsecurity** [lihaixin/portainer#1]
大佬你好，我用了你的面板一键部署SHADOWSOCKS-LIBEV，但我发下你容器里的SS-LIBEV太老了是3.1.13版本，我在这里改了参数
![photo_2019-07-31_14-59-32](https://user-images.githubusercontent.com/24518756/62190454-f8663600-b3a3-11e9-8b8f-0788ad656309.jpg)
，然后用你的面板部署SS-LIBEV容器，请问容器里的SS-LIBEV是3.3.0版本了吗？

**Comment by lihaixin** [comment]
已经是最新版的3.3.1

**Comment by embeddedsecurity** [comment]
> 已经是最新版的3.3.1

每次用你这面板在新的VPS上部署DOCKER SS-LIBEV，SS-LIBEV会是最新版吗？感谢你对互联网自由做出的贡献，让我们普通人也能在短时间内学会搭建翻墙服务器！

**Comment by embeddedsecurity** [comment]
> 已经是最新版的3.3.1

请问用你面板部署的docker-sslibev默认打开fast_open功能吗？据说fast_open功能会提速。你的回答会帮助许多使用你面板的人。

**Comment by lihaixin** [comment]
容器使用host网络模式，主机开启fast_open 

TCP快速打开
echo 3> /proc/sys/net/ipv4/tcp_fastopen
echo "net.ipv4.tcp_fastopen = 3" > /etc/sysctl.d/30-tcp_fastopen.conf

**Comment by embeddedsecurity** [comment]
> 容器使用host网络模式，主机开启fast_open
> 
> TCP快速打开
> echo 3> /proc/sys/net/ipv4/tcp_fastopen
> echo "net.ipv4.tcp_fastopen = 3" > /etc/sysctl.d/30-tcp_fastopen.conf

第一：你的docker ui面板在哪里可以打开host网络模式？
第二：
![image](https://user-images.githubusercontent.com/24518756/75796361-7eb97f00-5dae-11ea-9c83-a0244e7dd040.png)
热心回答他人问题的大佬事事顺利，复工老板就加薪，会有花姑娘陪伴终生,大佬身体健康！

**Comment by lihaixin** [comment]
1、创建后，重新复制创建一个，里面可以选择容器网络模式
2、已经更新到最新版了，请直接在模版里重新部署

**Comment by embeddedsecurity** [comment]
> 1、创建后，重新复制创建一个，里面可以选择容器网络模式
> 2、已经更新到最新版了，请直接在模版里重新部署

我前面有些话说错了，麻烦你看这个截图
![image](https://user-images.githubusercontent.com/24518756/75947114-3a2b0200-5eda-11ea-85c9-6819359e96fa.png)

**Comment by lihaixin** [comment]
你把源码下载下来自己创建镜像就可以，我这里不应该使用变量，应该用参数，早期的模板，没有考虑周到
